# Generated by Django 5.2.17 on 2026-09-02 13:52

from django.db import migrations


def fill_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    threshold = 2015

    for flat in Flat.objects.all():
        if flat.construction_year is not None:
            flat.new_building = flat.construction_year >= threshold
        else:
            flat.new_building = False
        flat.save()

def move_backward(apps, _schema_editor):
    flat_model = apps.get_model('property', 'Flat')
    flat_model.objects.all().update(new_building=None)

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(fill_new_building, move_backward)
    ]
