# Generated by Django 5.2.17 on 2026-09-04 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_alter_flat_liked_by'),
    ]

    operations = [

    ]
