# Generated by Django 5.2.17 on 2026-09-04 20:54

from django.db import migrations
import phonenumbers


def get_number(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    updated_count = 0

    for phone in Flat.objects.filter(owners_phonenumber='+70000000000'):
        phones = phone.owners_phonenumber
        if not phone:
            phone.owner_pure_phone = None
            phone.save(update_fields=['owner_pure_phone'])

        try:
            parsed_number = phonenumbers.parse(str(phones),'RU')
            is_valid = phonenumbers.is_valid_number(parsed_number)
        except phonenumbers.NumberParseException:
            is_valid = False
        if is_valid:
            phone.owner_pure_phone = phonenumbers.format_number(
                parsed_number,
                phonenumbers.PhoneNumberFormat.E164
            )
        else:
            phone.owner_pure_phone = None

    phone.save(update_fields=['owner_pure_phone'])
    updated_count += 1

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_alter_flat_liked_by'),
    ]

    operations = [
        migrations.RunPython(get_number, reverse_code=migrations.RunPython.noop),
    ]
