# Generated by Django 5.2.17 on 2026-09-04 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20260904_2108'),
        ('property', '0011_auto_20260904_2354'),
        ('property', '0013_auto_20260905_0006'),
    ]

    operations = [
    ]
