# Generated by Django 5.2.17 on 2026-09-21 10:56

from django.db import migrations


def get_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')


    for flat in Flat.objects.all().iterator():
        name = (flat.owner or '').strip()
        if not name:
            continue

        raw_phone = (flat.owners_phonenumber or '').strip()
        pure_phone = flat.owner_pure_phone or None

        owner, created = Owner.objects.get_or_create(
            name=name,
            defaults={
                'owner_number': raw_phone,
                'owner_pure_number': pure_phone,
            },
        )

        if not created:
            changed = []
            if raw_phone and not owner.owner_number:
                owner.owner_number = raw_phone
                changed.append('owner_number')
            if pure_phone and not owner.owner_pure_number:
                owner.owner_pure_number = pure_phone
                changed.append('owner_pure_number')
            if changed:
                owner.save(update_fields=changed)

def backwards(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_alter_flat_liked_by'),
    ]

    operations = [
        migrations.RunPython(get_owner, backwards),
    ]
