# Generated by Django 5.2.17 on 2026-09-21 13:07

from django.db import migrations


def get_owner_info(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')


    by_name = {
        owner.name.strip().lower():owner.pk
        for owner in Owner.objects.all()
    }


    links ={}
    for flat in Flat.objects.all().iterator():
        name =  (flat.owner or '').strip().lower()
        if not name:
            continue

        owner_pk = by_name.get(name.lower())
        if owner_pk is None:
            continue

        links.setdefault(owner_pk, []).append(flat.pk)

    for owner in Owner.objects.all().iterator():
        flat_id = links.get(owner.pk, [])
        owner.ownership.set(flat_id)


def backwards(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_auto_20260921_1356'),
    ]

    operations = [
        migrations.RunPython(get_owner_info, backwards),
    ]
